name: graph_application
description: "Flutter project for AOC"
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2
  xml2json: ^6.2.6
  window_manager: ^0.4.3
  file_picker: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
